name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu:22.04

    steps:
      - name: Checkout code
        uses: IP2B2/checkout@v3

      - name: Set up Node.js
        uses: IP2B2/setup-node@v3
        with:
          node-version: '16' # this is for compatbility with next.js

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push frontend Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Deploy to Server via SSH
        uses: IP2B2/ssh-action@v0.1.5  
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/DevOps
            docker-compose pull frontend
            docker-compose up -d frontend
