name: Deploy PR Frontend

on:
  pull_request:
    types: [labeled]

concurrency:
  group: pr-queue
  cancel-in-progress: false

jobs:
  deploy:
    if: github.event.label.name == 'ready-to-run'  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Compatibility with Next.js

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-testing:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push frontend Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-testing:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0  
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/DevOps
            docker-compose pull frontend-testing
            docker-compose up -d frontend-testing
