name: PR Initialization Labeler

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  label-init:
    runs-on: ubuntu-latest
    steps:
      - name: Check mergeable state
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            return context.payload.pull_request.mergeable_state !== 'dirty';
      - name: Add 'to-review' label
        if: steps.check.outputs.result == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: to-review
