name: Auto Label Ready-to-Run PRs

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
  pull-requests: write
  issues: write
  actions: write

jobs:
  label-ready:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { pull_request } = context.payload;
            const prNumber = pull_request.number;
            const repo = context.repo;

            // Skip if PR has conflicts
            if (pull_request.mergeable_state === 'dirty') {
              console.log('PR has merge conflicts — skipping label');
              return;
            }

            // Check if review has requested changes
            const reviews = await github.rest.pulls.listReviews({
              owner: repo.owner,
              repo: repo.repo,
              pull_number: prNumber,
            });

            const hasChangesRequested = reviews.data.some(r => r.state === 'CHANGES_REQUESTED');

            if (hasChangesRequested) {
              console.log('Changes requested — not labeling ready-to-run');
              return;
            }

            // Label PR as ready-to-run
            await github.rest.issues.addLabels({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: prNumber,
              labels: ['ready-to-run']
            });

            console.log('Labeled PR as ready-to-run');
