name: PR Merge Labeler

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write
  issues: write

jobs:
  label-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { pull_request } = context.payload;
            const prNumber = pull_request.number;
            const repo = context.repo;

            await github.rest.issues.addLabels({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: prNumber,
              labels: ['merged']
            });

            for (const label of ['ready-to-run', 'queued']) {
              await github.rest.issues.removeLabel({
                owner: repo.owner,
                repo: repo.repo,
                issue_number: prNumber,
                name: label
              }).catch(() => {});
            }

            const { data: openPRs } = await github.rest.pulls.list({
              owner: repo.owner,
              repo: repo.repo,
              state: 'open',
              base: pull_request.base.ref,
              sort: 'created',
              direction: 'asc'
            });

            const nextPR = openPRs.find(pr => {
              const labels = pr.labels.map(l => l.name);
              return !labels.includes('needs-work') && !labels.includes('ready-to-run');
            });

            if (nextPR) {
              await github.rest.issues.addLabels({
                owner: repo.owner,
                repo: repo.repo,
                issue_number: nextPR.number,
                labels: ['ready-to-run']
              });
            }

