name: Label Merged PRs

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write
  issues: write

jobs:
  label-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const repo = context.repo;

            await github.rest.issues.addLabels({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: pr.number,
              labels: ['merged']
            });
