name: PR Review Label Manager

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  issues: write

jobs:
  handle-review:
    runs-on: ubuntu-latest
    steps:
      - name: Get review state
        id: review
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const { owner, repo } = context.repo;

            const { data: reviews } = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number: pr.number
            });

            const latest = new Map();
            for (const r of reviews.reverse()) {
              if (!latest.has(r.user.login) && ['APPROVED', 'CHANGES_REQUESTED'].includes(r.state)) {
                latest.set(r.user.login, r.state);
              }
            }

            const values = [...latest.values()];
            const approvals = values.filter(v => v === 'APPROVED').length;
            const changesRequested = values.includes('CHANGES_REQUESTED');

            core.setOutput("approvals", approvals);
            core.setOutput("changesRequested", changesRequested);

      - name: Remove 'to-review'
        if: steps.review.outputs.approvals >= 1 || steps.review.outputs.changesRequested == 'true'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: to-review

      - name: Add 'ready-to-run'
        if: steps.review.outputs.approvals >= 1
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ready-to-run

      - name: Remove 'ready-to-run' (if changes requested)
        if: steps.review.outputs.changesRequested == 'true'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ready-to-run

      - name: Add 'needs-work'
        if: steps.review.outputs.changesRequested == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: needs-work

